### ISSUE TITLE
render code in align environment

### ISSUE THREAD

**Issue by dbpatankar** [dandavison/xenops#34]
This is a great package. I only wish it could use align environment to render the equations.

**Comment by dandavison** [comment]
Hi @dbpatankar, thanks. Regarding `align`, can you give a bit more detail of what's not working for you? Xenops does support `align` -- there are examples in the README, including the animation at the top of the page. Personally, `align` is the only environment I use for block math.

**Comment by dbpatankar** [comment]
Aah! Sorry to have bothered you. Probably there was some problem with my emacs config leading to this issue. A reboot has solved my problem. Closing it. Thanks!

**Comment by dandavison** [comment]
OK, great! No problem.
