### ISSUE TITLE
local subdirectory for all minted-directories

### ISSUE THREAD

**Issue by fab6** [dandavison/xenops#35]
Hi,
I am using `xenops` since a few days with orgmode; this works quite nice.

Though the directory gets filled with plenty of `_minted*` directories.
![image](https://user-images.githubusercontent.com/3047695/148107737-e9356086-8d8d-4164-bfa7-bd257494018c.png)

Is it possible to put them e.g. into a subfolder like `./.xenops`?
This is only a minor issue, but would be nice to have it a bit cleaner.

Thank you in advance!
Fab

**Comment by fab6** [comment]
ok, I just omit these with dired, that works for me fine
`          dired-omit-files "^\\.[^.].*| \\|^.DS_STORE$\\|^.projectile$\\|^_minted-.*"`

**Comment by dandavison** [comment]
Hi @fab6, sorry to be slow to reply --  I'm glad you found a solution. I think that this is sort of out of xenops's control -- is it possible that the `minted` LaTeX package has a variable controlling where these files go?

**Comment by fab6** [comment]
no problem, the omitting works good and thanks for the package!

**Comment by Elilif** [comment]
@fab6  Minted has some options for the cache, see [Minted Documentaion](http://tug.ctan.org/macros/latex/contrib/minted/minted.pdf), such as `cache` or `cachedir`. You can set the variable `org-latex-packages-alist` to set these options in Emacs. For instance:
```
(add-to-list 'org-latex-packages-alist
	     '("cache=false" "minted" t))
```

**Comment by fab6** [comment]
thank you!
