### ISSUE TITLE
tex-buf is no longer provided by the auctex package.

### ISSUE THREAD

**Issue by Elilif** [dandavison/xenops#38]
tex-buf.el is merged into tex.el in AUCTeX 13

**Comment by jfab-123** [comment]
I cannot install xenops because I get an error related to this. How can I fix it?

**Comment by lizhuohua** [comment]
We can consider the patch in [this PR](https://github.com/tom-tan/auctex-latexmk/pull/40).

**Comment by dandavison** [comment]
Hi all, and thanks @lizhuohua, I've applied the same patch as the one you link to. Can anyone confirm that this fixes the problem you're encountering? (The new xenops should be available on MELPA in a few hours.)

**Comment by Elilif** [comment]
Confirmed, Thank you for your fix.

**Comment by dandavison** [comment]
Excellent, thanks all.
