### ISSUE TITLE
Math not rendering in doom-emacs

### ISSUE THREAD

**Issue by AugustoRiedinger** [dandavison/xenops#43]
Pretty much title, the equations are not rendering wth `xenops-mode` activated. [Here](https://imgur.com/7iyIBw8) is an image of what's happening. 

`xenops-doctor` returns no errors (`Xenops is healthy`).

**Comment by dandavison** [comment]
Hi @AugustoRiedinger, the exclamation mark character contains information about the error, via hover and right-click. The README describes how to access this information for debugging: https://github.com/dandavison/xenops#31-rendering-math-tables-and-tikz-content (section 5 "What if something went wrong?"). Could you try debugging following those techniques?

**Comment by AugustoRiedinger** [comment]
Hello. You are right, it was a problem with my LaTeX configuration. As LaTeX couldn't compile, `xenops` didn't render. Once I fixed it, `xenops` started working as expeted. Thanks for the insight and the awesome package. Regards.
