### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by Shea690901** [dandavison/xenops#52]
I've installed `xenops 20220421.1320` via melpa but have problems with loading it...
Despite having installed all listed dependencies (in newer versions than listed) I'm missing a dependency for `'preview`!
Which package is required for this symbol?

**Comment by dandavison** [comment]
Hi @Shea690901, the `auctex` package provides this symbol. Could you try a fresh install of everything? The way I would do this is something like:

```
M-x package-refresh-contents
M-x package-delete xenops-$VERSION
M-x package-delete auctex-$VERSION
```

Restart emacs

```
M-x package-refresh-contents
M-x package-install xenops
```

Installing xenops should install auctex automatically.

**Comment by Shea690901** [comment]
Ack....

While I had installed auctex, it was _without_ preview-latex :(

Thanks for the info :)
