### ISSUE TITLE
Xenops is not compatible with auctex (13.1.4)

### ISSUE THREAD

**Issue by LuminaDCIX** [dandavison/xenops#54]
I use xenops in org-mode. 

```
(add-hook 'org-mode-hook #'xenops-mode)
```

It looks like Xenops is not working with the new version of auctex (13.1.4)?

**Comment by dandavison** [comment]
Hi @LuminaDCIX, can you post the errors that you're getting?

**Comment by LuminaDCIX** [comment]
Hi!
I didn't encounter significant errors. But the xenops-related commands all fail (e.g. xenops-increase-size). The rendering of formulas also gets stuck for a while, as if xenops-mode is not turned on. Emacs seems to still be using auctex for latex preview.

**Comment by LuminaDCIX** [comment]
I finally found out that it was a problem with org-fragtog. Thx

**Comment by dandavison** [comment]
OK, excellent, happy you got to the bottom of that.
