### ISSUE TITLE
Continue after error

### ISSUE THREAD

**Issue by kchousos** [dandavison/xenops#58]
Is there a way to continue the process after the latex compiler prints an error?

In my case, I use xelatex and the xgreek package. This package brings out some warnings, but the final xdv file is compiled fine. If I run the commands manually, the svg file is created correctly, but xenops stops before dvisvgm is executed. My relevant configuration is the following:

```emacs-lisp
(use-package xenops
  :straight t
  :config
  (setq xenops-math-image-scale-factor 1.6))

(add-to-list 'org-latex-packages-alist
	     '("cache=false" "minted" t))

(setq xenops-math-latex-process-alist
      '(
       (dvisvgm :programs
                ("xelatex" "dvisvgm")
                :description "xdv > svg"
                :message "you need to install the programs: xelatex and dvisvgm."
                :image-input-type "xdv"
                :image-output-type "svg"
                :image-size-adjust (0.5 . 0.5)
                :latex-compiler
                ("xelatex -no-pdf -interaction=nonstopmode -shell-escape -output-directory %o %f")
                :image-converter
                ("dvisvgm %f -n -b min -c %S -o %O"))
        (dvipng :programs
               ("xelatex" "dvipng")
               :description "dvi > png"
               :message "you need to install the programs: latex and dvipng."
               :image-input-type "dvi"
               :image-output-type "png"
               :image-size-adjust
               (1.0 . 1.0)
               :latex-compiler
               ("xelatex -interaction nonstopmode -shell-escape -output-format dvi -output-directory %o %f")
               :image-converter
               ("dvipng -D %D -T tight -o %O %f"))
       (imagemagick :programs
                    ("latex" "convert")
                    :description "pdf > png"
                    :message "you need to install the programs: latex and imagemagick."
                    :image-input-type "pdf"
                    :image-output-type "png"
                    :image-size-adjust
                    (1.0 . 1.0)
                    :latex-compiler
                    ("pdflatex -interaction nonstopmode -shell-escape -output-directory %o %f")
                    :image-converter
                    ("convert -density %D -trim -antialias %f -quality 100 %O"))))

(setq xenops-math-latex-process 'dvisvgm)
(add-hook 'latex-mode-hook #'xenops-mode)
(add-hook 'LaTeX-mode-hook #'xenops-mode)
(add-hook 'org-mode-hook #'xenops-mode)
```

**Comment by dandavison** [comment]
Hi @kchousos, I'm happy you're using Xenops! I'm not sure about this. By the way, I should make it clear that I don't have much time to work on Xenops right now, so this might have to be something you investigate unfortunately. A couple of thoughts are:

- Might the problem affect the org community also? Seeing as xenops's LaTeX infrastructure was copied from org. In which case maybe they have answers to this.
- I wonder if you can make progress by writing a shell wrapper for your xelatex and using that wrapper as your `:latex-compiler`?

**Comment by kchousos** [comment]
I actually fixed it by passing the `monogreek` option in `usepackage{xgreek}`, which results in `usepackage[monogreek]{xgreek}`. Although the option is supposedly the default, setting it explicitly makes the errors go away. This actually was a good opportunity to solve this issue, because it has been bugging me and creating problems for some time now.

Anyways, thank you for your time and your awesome package!
