### ISSUE TITLE
xenops-reveal-on-entry messes with cursor position

### ISSUE THREAD

**Issue by quarkQuark** [dandavison/xenops#59]
When `xenops-reveal-on-entry` is enabled and a previously completed fragment (say, `\(x\)`) is edited, typing an underscore immediately moves the cursor to the beginning of the fragment, leading to input such as `\(1x_{}\)` instead of `\(x_{1}\)`. I have checked that this does not happen when `xenops-reveal-on-entry` is set to `nil`.

**Comment by fanzhuyifan** [comment]
Hi, I am using cdlatex and also experiencing this issue. I found a work-around by redefining [xenops-math-reveal](https://github.com/dandavison/xenops/blob/61f4fe7b5cc2549ea7363635307279becac53ea7/lisp/xenops-math.el#L161) and removing the `goto-char`:

```
(defun xenops-math-reveal (element)
  "Remove image overlay for ELEMENT.
If a prefix argument is in effect, also delete its cache file."
  (xenops-element-overlays-delete element)
  (if current-prefix-arg
      (delete-file (xenops-math-get-cache-file element)))
  ;; TODO: is :begin-content for block math off by one?
  (let ((element-type (plist-get element :type))
        (begin-content (plist-get element :begin-content)))
    )
  (xenops-math-render-below-maybe element))
```

Just place this in your emacs init file after loading xenops

**Comment by quarkQuark** [comment]
Thanks! That seems to work well. I would be curious to know what the intended purpose is for `goto-char` in that function. Might be worth you submitting your work-around as a pull request.
