### ISSUE TITLE
tikz not rendered properly (neither in orgmode nor .tex)

### ISSUE THREAD

**Issue by pulledlamb** [dandavison/xenops#68]
<img width="381" alt="Screen Shot 2024-01-03 at 12 25 19 pm" src="https://github.com/dandavison/xenops/assets/81538877/12e34537-f29d-4b03-bb49-f0c563697f87">

it has tried, but not to any satisfaction.

**Comment by dandavison** [comment]
Hi @pulledlamb, have you tried the steps in the "What if something went wrong?" section here? https://github.com/dandavison/xenops?tab=readme-ov-file#31-rendering-math-tables-and-tikz-content

**Comment by pulledlamb** [comment]
> Hi @pulledlamb, have you tried the steps in the "What if something went wrong?" section here? https://github.com/dandavison/xenops?tab=readme-ov-file#31-rendering-math-tables-and-tikz-content

Hi @dandavison,

thanks for quick reply. Yes I've tried that, xenops is healthy.

**Comment by dandavison** [comment]
OK, can you post a minimal example LaTeX document that's not working correctly for you? Does it render correctly when you use latex at the command line, without Emacs?

**Comment by pulledlamb** [comment]
> OK, can you post a minimal example LaTeX document that's not working correctly for you? Does it render correctly when you use latex at the command line, without Emacs?

if that means pdflatex -pdf  .tex, yes it works; in fact export to pdf from .org or .tex in emacs works too.

<img width="750" alt="Screen Shot 2024-01-03 at 1 11 02 pm" src="https://github.com/dandavison/xenops/assets/81538877/9db4ddba-5dbb-4f51-b43e-661112ad1ebe">

And here's the latex code i used:
`\documentclass[a4paper, 11pt]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{tikz}
\usetikzlibrary{shapes.misc, arrows, graphs}

\begin{document}

\begin{tikzpicture}
  \graph{a -> b;};
\end{tikzpicture}
\end{document}
`

**Comment by pulledlamb** [comment]
update: seems to be a dvisvgm problem related to this line
```
image-converter ("dvisvgm %f -n -b %B -c %S -o %O")
```

**Comment by pulledlamb** [comment]
here's what seems to help; enable ps for dvisvgm
```
(setq xdvsvgm
        '(xdvsvgm
          :programs ("latex" "dvisvgm")
     :description "dvi > svg"
     :message "you need to install the programs: latex and dvisvgm."
     :image-input-type "dvi"
     :image-output-type "svg"
     :image-size-adjust (1.7 . 1.5)
     :latex-compiler ("latex -interaction nonstopmode -shell-escape -output-format dvi -output-directory %o %f")
     :image-converter ("dvisvgm %f -n -b %B -c %S -o %O --libgs=/opt/homebrew/Cellar/ghostscript/10.02.1/lib/libgs.10.dylib")))
  (with-eval-after-load 'xenops
    (add-to-list 'xenops-math-latex-process-alist xdvsvgm)
    (setq xenops-math-latex-process  'xdvsvgm))
```
