### ISSUE TITLE
Support other documentclass

### ISSUE THREAD

**Issue by fuyu0425** [dandavison/xenops#7]
Thanks for this fantastic package!
However, is there any possibility to support other documentclass? 
For example, 
```
\documentclass[final, conference]{IEEEtran}
\IEEEoverridecommandlockouts
``` 
Because the `\IEEEoverridecommandlockouts` is defined in `IEEEtran.cls`, and xenops only use `article` documentclass, then it fails.

**Comment by dandavison** [comment]
Hi @fuyu0425, thanks! Yes, let's get this working for you. Are you sure it's not working already? I just tested this out with a document like this:

```latex
\documentclass[final, conference]{IEEEtran}
\IEEEoverridecommandlockouts
\usepackage{amsmath}

\begin{document}

Hello world!

\end{document}
```

and when I executed `(xenops-math-latex-make-preamble-lines)` it did correctly extract the preamble. Can you tell me exactly what error you're seeing?

**Comment by fuyu0425** [comment]
It seems that the `(xenops-math-latex-make-preamble-lines)` works fine.
But
The buffer `Xenops external command output`
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=latex)
 \write18 enabled.
entering extended mode

(/var/folders/vg/4l8mg2ss5m36qk342npvgw240000gq/T/ad3a91564f36010d89000a3bc131b
8abc734141c.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics-def/dvips.def)
(/usr/local/texlive/2018/texmf-dist/tex/latex/graphics/dvipsnam.def))
! Undefined control sequence.
<recently read> \IEEEoverridecommandlockouts 
                                             
l.3 \IEEEoverridecommandlockouts

```
The buffer `Xenops external command input`
```
\documentclass{article}
\usepackage[usenames]{color}
\IEEEoverridecommandlockouts

```
The documentclass becomes `article` here

**Comment by dandavison** [comment]
Thanks @fuyu0425!

By the way, I'm happy you're using Xenops. What the project needs right now is some users who are happy to open issues and tell me what needs working on. So, I will respond promptly to any questions/problems you have about Xenops (and you can also email me directly at dandavison7@gmail.com).

OK, explanation of your problem: Xenops uses some LaTeX configuration code from org-mode. This makes sense because org-mode is part of Emacs, and also supports LaTeX fragment preview, and supports SVG images.

The problem you are seeing is due to `org-format-latex-header`. One solution is simply to set this variable, just changing the first line and leaving the rest the same, so like this:

```emacs-lisp
(setq org-format-latex-header "\\documentclass[final, conference]{IEEEtran}
\\usepackage[usenames]{color}
[PACKAGES]
[DEFAULT-PACKAGES]
\\pagestyle{empty}             % do not remove
% The settings below are copied from fullpage.sty
\\setlength{\\textwidth}{\\paperwidth}
\\addtolength{\\textwidth}{-3cm}
\\setlength{\\oddsidemargin}{1.5cm}
\\addtolength{\\oddsidemargin}{-2.54cm}
\\setlength{\\evensidemargin}{\\oddsidemargin}
\\setlength{\\textheight}{\\paperheight}
\\addtolength{\\textheight}{-\\headheight}
\\addtolength{\\textheight}{-\\headsep}
\\addtolength{\\textheight}{-\\footskip}
\\addtolength{\\textheight}{-3cm}
\\setlength{\\topmargin}{1.5cm}
\\addtolength{\\topmargin}{-2.54cm}")
```

Whether that is the optimal solution, I am not 100% sure. But I am thinking that whatever is the optimal solution for org-mode users who are using  `IEEEtran.cls`, would also be the solution for Xenops users, if you see what I mean, because currently Xenops shares some LaTeX configuration mechanisms with org-mode.

Here's the documentation of the variable:

```
org-format-latex-header is a variable defined in ‘org.el’.
Its value is shown below.

Documentation:
The document header used for processing LaTeX fragments.
It is imperative that this header make sure that no page number
appears on the page.  The package defined in the variables
‘org-latex-default-packages-alist’ and ‘org-latex-packages-alist’
will either replace the placeholder "[PACKAGES]" in this
header, or they will be appended.

You can customize this variable.

Value:
"\\documentclass{article}
\\usepackage[usenames]{color}
[PACKAGES]
[DEFAULT-PACKAGES]
\\pagestyle{empty}             % do not remove
% The settings below are copied from fullpage.sty
\\setlength{\\textwidth}{\\paperwidth}
\\addtolength{\\textwidth}{-3cm}
\\setlength{\\oddsidemargin}{1.5cm}
\\addtolength{\\oddsidemargin}{-2.54cm}
\\setlength{\\evensidemargin}{\\oddsidemargin}
\\setlength{\\textheight}{\\paperheight}
\\addtolength{\\textheight}{-\\headheight}
\\addtolength{\\textheight}{-\\headsep}
\\addtolength{\\textheight}{-\\footskip}
\\addtolength{\\textheight}{-3cm}
\\setlength{\\topmargin}{1.5cm}
\\addtolength{\\topmargin}{-2.54cm}"
```

**Comment by dandavison** [comment]
I've added this to the README in 2a72cf519bda25ee8852672e14b6c265388bc74b. Thanks again for pointing this out!

**Comment by fuyu0425** [comment]
ok thanks!
